#include "Cone.h"




void Cone::SaisirInfos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C5C begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C5C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cone::CalculerVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C5F begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Cone::Cone()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB6 begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Cone::~Cone()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DCD begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DCD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cone::AfficherVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-68372c94:13c7292c9c3:-8000:0000000000000B75 begin
{
    
}
// section -64--88-1-33-68372c94:13c7292c9c3:-8000:0000000000000B75 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
