#include "Cube.h"




void Cube::SaisirInfos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C54 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cube::CalculerVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C58 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C58 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Cube::Cube()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB0 begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Cube::~Cube()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DC9 begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DC9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cube::AfficherVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-68372c94:13c7292c9c3:-8000:0000000000000B71 begin
{
    
}
// section -64--88-1-33-68372c94:13c7292c9c3:-8000:0000000000000B71 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
