#include "Formes3D.h"




void Formes3D::SaisirInfos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C45 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Formes3D::CalculerVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C49 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C49 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Formes3D::AfficherVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C4D begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C4D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Formes3D::Formes3D()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB2 begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Formes3D::~Formes3D()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DC7 begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DC7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
