#include "Sphere.h"




void Sphere::SaisirInfos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C62 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C62 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Sphere::CalculerVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C66 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C66 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Sphere::Sphere()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB4 begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DB4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Sphere::~Sphere()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DCB begin
{
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DCB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Sphere::AfficherVolume()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-68372c94:13c7292c9c3:-8000:0000000000000B73 begin
{
    
}
// section -64--88-1-33-68372c94:13c7292c9c3:-8000:0000000000000B73 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
