#include "Utilisateur.h"




void Utilisateur::ChoisirForme(Formes3D &Forme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C34 begin
{
    
}
// section -84-16-32-52-7d251175:13b5f99e2cb:-8000:0000000000000C34 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::TraiterForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DC2 begin
{
    
}
// section -64--88-1-58-3b7b9caf:13c10f71ce9:-8000:0000000000000DC2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
